version: '3'
services:
  database:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD : docker
      POSTGRES_DB : mydbphoto
  
  adminer:
    image: adminer      
    depends_on:
      - database
    ports:
      - 8080:8080
