version: '3'
services:
  database:
    image: postgres
    ports:
      - 5435:5433
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD : docker
      POSTGRES_DB : mydbphoto
    volumes:
      - db-photo-upload-service:/var/lib/postgresql/data
  
  adminer:
    image: adminer      
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
  
volumes:
  db-photo-upload-service:
